# Generated by Django 5.0.1 on 2024-04-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='qr_img',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='QR/'),
        ),
    ]
