# Generated by Django 5.0.1 on 2024-04-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_qr_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='coupon_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
