# Generated by Django 5.0.1 on 2024-04-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_eventlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventList',
        ),
    ]
