# Generated by Django 5.0.1 on 2024-04-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_eventlist_month_alter_eventlist_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=20)),
                ('opt', models.CharField(max_length=20)),
            ],
        ),
    ]
