# Generated by Django 5.0.1 on 2024-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_scanneddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
