# Generated by Django 5.0.1 on 2024-04-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_genscanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('usn', models.CharField(max_length=10)),
            ],
        ),
    ]
