# Generated by Django 5.0.1 on 2024-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_usnapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnapproval',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
